version: '3'

networks:
  rictms4b:

services:
  site:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: nginx_rictms4b
    ports:
      - 81:80
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - redis
    networks:
      - rictms4b

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: php_rictms4b
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - rictms4b

  redis:
    image: redis:alpine
    container_name: redis_rictms4b
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - rictms4b

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: composer_rictms4b
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - rictms4b

  npm:
    image: node:lts-hydrogen
    container_name: npm_rictms4b
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - rictms4b

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: artisan_rictms4b
    volumes:
      - ./src:/var/www/html:delegated
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - rictms4b

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_rictms4b
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - rictms4b
